### ISSUE TITLE
error on npm install

### ISSUE THREAD

**Issue by magnoou** [mgechev/scalable-architecture-demo#8]
[X ] bug report 

npm version: 3.10.10
node version: 7.2.1
windows 10
angular-seed version 0.0.0 - 6380efe751

I'm getting the following after npm install

TSError: ⨯ Unable to compile TypeScript
Cannot find type definition file for 'node'. (2688)
gulpfile.ts (1,23): Cannot find module 'gulp'. (2307)
gulpfile.ts (2,23): Cannot find module 'gulp-util'. (2307)
gulpfile.ts (3,30): Cannot find module 'run-sequence'. (2307)
gulpfile.ts (5,20): Cannot find module './tools/config'. (2307)
gulpfile.ts (6,47): Cannot find module './tools/utils'. (2307)

I think it might be a dependency error with rxjs, but I can't get it to work

angular-seed@0.0.0
`-- UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12
npm ERR! peer dep missing: rxjs@^5.4.0, required by @ngrx/store@2.2.3

**Comment by zhekaus** [comment]
I have the same problem.

**Comment by vredchenko** [comment]
Same here:

```
npm i
npm WARN deprecated compodoc@0.0.15: Compodoc has moved to @compodoc/compodoc
npm WARN deprecated express@2.5.11: express 2.x series is deprecated
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated connect@1.9.2: connect 1.x series is deprecated
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> fsevents@1.1.2 install /Users/vredchenko/dev/scalable-architecture-demo/node_modules/fsevents
> node install

[fsevents] Success: "/Users/vredchenko/dev/scalable-architecture-demo/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> node-sass@3.13.1 install /Users/vredchenko/dev/scalable-architecture-demo/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/darwin-x64-48_binding.node
Download complete  ⸩ ⠋ :
Binary saved to /Users/vredchenko/dev/scalable-architecture-demo/node_modules/node-sass/vendor/darwin-x64-48/binding.node
Caching binary to /Users/vredchenko/.npm/node-sass/3.13.1/darwin-x64-48_binding.node

> node-sass@3.13.1 postinstall /Users/vredchenko/dev/scalable-architecture-demo/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/vredchenko/dev/scalable-architecture-demo/node_modules/node-sass/vendor/darwin-x64-48/binding.node
Testing binary
Binary is fine

> angular-seed@0.0.0 postinstall /Users/vredchenko/dev/scalable-architecture-demo
> gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver && gulp print.banner

[15:16:11] Requiring external module ts-node/register

/Users/vredchenko/dev/scalable-architecture-demo/node_modules/ts-node/src/index.ts:312
          throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
                ^
TSError: ⨯ Unable to compile TypeScript
Cannot find type definition file for 'node'. (2688)
gulpfile.ts (1,23): Cannot find module 'gulp'. (2307)
gulpfile.ts (2,23): Cannot find module 'gulp-util'. (2307)
gulpfile.ts (3,30): Cannot find module 'run-sequence'. (2307)
gulpfile.ts (5,20): Cannot find module './tools/config'. (2307)
gulpfile.ts (6,47): Cannot find module './tools/utils'. (2307)
    at getOutput (/Users/vredchenko/dev/scalable-architecture-demo/node_modules/ts-node/src/index.ts:312:17)
    at /Users/vredchenko/dev/scalable-architecture-demo/node_modules/ts-node/src/index.ts:343:18
    at Object.compile (/Users/vredchenko/dev/scalable-architecture-demo/node_modules/ts-node/src/index.ts:476:19)
    at Module.m._compile (/Users/vredchenko/dev/scalable-architecture-demo/node_modules/ts-node/src/index.ts:406:44)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/vredchenko/dev/scalable-architecture-demo/node_modules/ts-node/src/index.ts:409:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-seed@0.0.0 postinstall: `gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver && gulp print.banner`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-seed@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.4.1 → 5.4.2    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯


npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vredchenko/.npm/_logs/2017-10-01T12_16_12_631Z-debug.log
```

Attaching npm's log to this ticket.

```
ng version
Your global Angular CLI version (1.4.3) is greater than your local
version (1.4.1). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.1
node: 6.10.0
os: darwin x64
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.4.1
@angular/compiler-cli: 4.3.6
typescript: 2.3.4
```

```
tsc -v
Version 2.3.4

node -v
v6.10.0

npm -v
5.4.1
```

What's the rationale behind using `gulp` btw? I had the impression it's pretty much redundant nowadays

[2017-10-01T12_16_12_631Z-debug.log](https://github.com/mgechev/scalable-architecture-demo/files/1347113/2017-10-01T12_16_12_631Z-debug.log)

**Comment by janckerchen** [comment]
me too
```
> angular-seed@0.0.0 postinstall /opt/dev/+demos/scalable-architecture-demo
> gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver && gulp print.banner

[23:50:29] Requiring external module ts-node/register

/opt/dev/+demos/scalable-architecture-demo/node_modules/ts-node/src/index.ts:312
          throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
                ^
TSError: ⨯ Unable to compile TypeScript
Cannot find type definition file for 'node'. (2688)
gulpfile.ts (1,23): Cannot find module 'gulp'. (2307)
gulpfile.ts (2,23): Cannot find module 'gulp-util'. (2307)
gulpfile.ts (3,30): Cannot find module 'run-sequence'. (2307)
gulpfile.ts (5,20): Cannot find module './tools/config'. (2307)
gulpfile.ts (6,47): Cannot find module './tools/utils'. (2307)
    at getOutput (/opt/dev/+demos/scalable-architecture-demo/node_modules/ts-node/src/index.ts:312:17)
    at /opt/dev/+demos/scalable-architecture-demo/node_modules/ts-node/src/index.ts:343:18
    at Object.compile (/opt/dev/+demos/scalable-architecture-demo/node_modules/ts-node/src/index.ts:476:19)
    at Module.m._compile (/opt/dev/+demos/scalable-architecture-demo/node_modules/ts-node/src/index.ts:406:44)
    at Module._extensions..js (module.js:635:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/opt/dev/+demos/scalable-architecture-demo/node_modules/ts-node/src/index.ts:409:12)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-seed@0.0.0 postinstall: `gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver && gulp print.banner`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-seed@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jason/.npm/_logs/2017-10-01T15_50_30_140Z-debug.log
```

**Comment by vredchenko** [comment]
@janckerchen Obviously things have moved on in the past 6 months since anyone contributed to this repo (new versions of angular, typescript, npm, etc).

For my purposes the solution is to just borrow code organisation and separation of concerns demonstrated here and manually graft them onto a modern angular setup generated by ng cli
